# Generated by Django 4.2.7 on 2023-12-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
