# Generated by Django 5.0.1 on 2024-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0006_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUSADataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_or_country', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('state_name', models.CharField(default=None, max_length=50)),
                ('country', models.CharField(default=None, max_length=50)),
                ('lattitude', models.CharField(default=None, max_length=50)),
                ('longitude', models.CharField(default=None, max_length=50)),
                ('population', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
