# Generated by Django 5.0.1 on 2024-01-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationusadatamodel',
            old_name='country',
            new_name='county',
        ),
    ]
